### ISSUE TITLE
Linux: Cannot find module '../build/Release/canvas'

### ISSUE THREAD

**Issue by azat-io** [ben-eb/postcss-resemble-image#5]
**Node.js** v.6.9.1

Also installed canvas npm package. Plugin `postcss-resemble-image` not works for me:

```
root@pc:~/Dev/prj# node ./node_modules/.bin/gulp postcss
[19:15:42] Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/Dev/prj/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/root/Dev/prj/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/Dev/prj/node_modules/canvas/lib/canvas.js:13:14)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/root/Dev/prj/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by ben-eb** [comment]
Hi @azat-io,

Does this thread help at all? https://github.com/Automattic/node-canvas/issues/284

We're currently investigating a Node-only solution which should make the module easier to configure (especially on Windows).

https://github.com/ben-eb/postcss-resemble-image/pull/3

**Comment by ben-eb** [comment]
`2.0.0` has now been released, and it removes this dependency. 😄
